export interface SeedCategory {
  id: string;
  slug: string;
  name: string;
  description: string;
  imageUrl: string;
  sortOrder: number;
  isActive: boolean;
  seoTitle: string;
  seoDescription: string;
}

export interface SeedVariant {
  id: string;
  cjVariantId: string;
  sku: string;
  option1Name?: string;
  option1Value?: string;
  option2Name?: string;
  option2Value?: string;
  price: number;
  compareAtPrice?: number;
  costPrice: number;
  shippingCost: number;
  inventoryQuantity: number;
  weight: number;
  isActive: boolean;
}

export interface SeedProduct {
  id: string;
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  categoryId: string;
  brandName: string;
  status: "published" | "draft" | "archived";
  riskStatus: "normal" | "review_required" | "restricted" | "rejected";
  featured: boolean;
  bestseller: boolean;
  newArrival: boolean;
  seoTitle: string;
  seoDescription: string;
  baseCurrency: string;
  basePrice: number;
  compareAtPrice?: number;
  cjProductId: string;
  cjProductSku: string;
  productRating: number;
  reviewCount: number;
  images: {
    id: string;
    publicUrl: string;
    altText: string;
    isPrimary: boolean;
    sortOrder: number;
  }[];
  variants: SeedVariant[];
  specifications: Record<string, string>;
  features: string[];
}

export const CATEGORIES: SeedCategory[] = [
  {
    id: "cat-home-kitchen",
    slug: "home-kitchen",
    name: "Home & Kitchen",
    description: "Elevated essentials designed for culinary precision and serene living spaces.",
    imageUrl: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 1,
    isActive: true,
    seoTitle: "Home & Kitchen - Premium Curated Living | MYCHOICE.in",
    seoDescription: "Explore luxury pour-over kettles, aroma diffusers, and chef-grade kitchen essentials.",
  },
  {
    id: "cat-pet-supplies",
    slug: "pet-supplies",
    name: "Pet Supplies",
    description: "Thoughtfully crafted accessories and wellness items for your beloved companions.",
    imageUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 2,
    isActive: true,
    seoTitle: "Pet Supplies - Modern Living for Pets | MYCHOICE.in",
    seoDescription: "Discover orthopedic memory foam pet loungers, automated water fountains, and premium leashes.",
  },
  {
    id: "cat-beauty-personal-care",
    slug: "beauty-personal-care",
    name: "Beauty & Personal Care",
    description: "Science-backed skincare tools and self-care rituals for radiant living.",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 3,
    isActive: true,
    seoTitle: "Beauty & Personal Care - Elevated Self Care | MYCHOICE.in",
    seoDescription: "Shop sonic microcurrent facial devices, rose quartz rollers, and ionic hair stylers.",
  },
  {
    id: "cat-ornaments-fashion-accessories",
    slug: "ornaments-fashion-accessories",
    name: "Ornaments & Fashion Accessories",
    description: "Refined jewelry, premium leather accents, and timeless personal adornments.",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 4,
    isActive: true,
    seoTitle: "Fashion Accessories & Fine Ornaments | MYCHOICE.in",
    seoDescription: "18K gold vermeil pendants, titanium rings, and Italian leather cardholders.",
  },
  {
    id: "cat-phone-tech-accessories",
    slug: "phone-tech-accessories",
    name: "Phone & Tech Accessories",
    description: "Sleek workspace hardware and magnetic wireless charging gear built for tomorrow.",
    imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 5,
    isActive: true,
    seoTitle: "Phone & Tech Accessories - High-End Desk Gear | MYCHOICE.in",
    seoDescription: "3-in-1 magnetic wireless chargers, aluminum laptop stands, and braided 100W GaN cables.",
  },
  {
    id: "cat-fitness-wellness",
    slug: "fitness-wellness",
    name: "Fitness & Wellness",
    description: "High-performance recovery gear and active lifestyle essentials designed for vitality.",
    imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 6,
    isActive: true,
    seoTitle: "Fitness & Wellness - Precision Recovery Tools | MYCHOICE.in",
    seoDescription: "Deep tissue percussion massage guns, natural cork yoga mats, and smart resistance jump ropes.",
  },
  {
    id: "cat-eco-friendly-sustainable",
    slug: "eco-friendly-sustainable",
    name: "Eco-Friendly & Sustainable",
    description: "Consciously engineered zero-waste goods made from pure, earth-first materials.",
    imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 7,
    isActive: true,
    seoTitle: "Eco-Friendly & Sustainable Essentials | MYCHOICE.in",
    seoDescription: "Vacuum ceramic tumblers, organic beeswax wraps, and wheat straw bento boxes.",
  },
  {
    id: "cat-baby-kids",
    slug: "baby-kids",
    name: "Baby & Kids",
    description: "Gentle, certified non-toxic essentials tailored for nurture and serene rest.",
    imageUrl: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1000&q=80",
    sortOrder: 8,
    isActive: true,
    seoTitle: "Baby & Kids - Thoughtfully Pure Nursery Care | MYCHOICE.in",
    seoDescription: "Silicone suction feeding sets, organic muslin swaddle blankets, and white noise sound machines.",
  },
];

export const DEMO_PRODUCTS: SeedProduct[] = [
  // 1. HOME & KITCHEN (3 products)
  {
    id: "prod-hk-1",
    slug: "minimalist-ultrasonic-aroma-diffuser",
    name: "Minimalist Ultrasonic Aroma Diffuser & Ambient Light",
    shortDescription: "Whisper-quiet ceramic ultrasonic diffuser with subtle ambient warm glow.",
    description: "Sculpted from matte stone-finish ceramic, this ultrasonic diffuser purifies your atmosphere with micro-fine botanical mist while emitting a calm candle-like ambient illumination. Designed for modern living spaces requiring acoustic tranquility and understated elegance.",
    categoryId: "cat-home-kitchen",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "Minimalist Ultrasonic Aroma Diffuser | MYCHOICE.in",
    seoDescription: "Whisper-quiet ceramic aroma diffuser with gentle candle ambient lighting.",
    baseCurrency: "USD",
    basePrice: 58.00,
    compareAtPrice: 78.00,
    cjProductId: "CJ-HK-001",
    cjProductSku: "CJ-DIFF-CERAMIC",
    productRating: 4.9,
    reviewCount: 38,
    images: [
      { id: "img-hk-1a", publicUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=1000&q=80", altText: "Ultrasonic Diffuser Ceramic Finish", isPrimary: true, sortOrder: 1 },
      { id: "img-hk-1b", publicUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1000&q=80", altText: "Diffuser Ambient Mist", isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-hk-1-w", cjVariantId: "CJ-V-DIFF-W", sku: "MY-DIFF-WHT", option1Name: "Finish", option1Value: "Sandstone White", price: 58.00, compareAtPrice: 78.00, costPrice: 19.50, shippingCost: 4.80, inventoryQuantity: 120, weight: 650, isActive: true },
      { id: "var-hk-1-b", cjVariantId: "CJ-V-DIFF-B", sku: "MY-DIFF-BLK", option1Name: "Finish", option1Value: "Basalt Charcoal", price: 58.00, compareAtPrice: 78.00, costPrice: 19.50, shippingCost: 4.80, inventoryQuantity: 85, weight: 650, isActive: true },
    ],
    specifications: { "Capacity": "300ml", "Run Time": "Up to 10 hours", "Coverage": "450 sq ft", "Noise Level": "< 20 dB", "Material": "Handmade Matte Ceramic & BPA-Free Polymer" },
    features: ["Whisper-quiet ultrasonic diffusion", "Automatic shut-off when dry", "Warm candlelight LED mode", "Continuous & intermittent mist timers"],
  },
  {
    id: "prod-hk-2",
    slug: "precision-thermal-gooseneck-kettle",
    name: "Precision Thermal Gooseneck Electric Pour-Over Kettle",
    shortDescription: "Counter-balanced ergonomic pour-over kettle with 1-degree temperature control.",
    description: "Engineered for specialty coffee enthusiasts and tea connoisseurs. Features a counter-balanced handle, 1-degree temperature precision dial, and a precision-fluted gooseneck spout that provides laminar, drip-free water flow control.",
    categoryId: "cat-home-kitchen",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: false,
    newArrival: true,
    seoTitle: "Precision Gooseneck Pour-Over Kettle | MYCHOICE.in",
    seoDescription: "Variable temperature electric pour-over kettle with flow-control gooseneck spout.",
    baseCurrency: "USD",
    basePrice: 94.00,
    compareAtPrice: 125.00,
    cjProductId: "CJ-HK-002",
    cjProductSku: "CJ-KET-GOOSE",
    productRating: 4.85,
    reviewCount: 42,
    images: [
      { id: "img-hk-2a", publicUrl: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=1000&q=80", altText: "Gooseneck Kettle Matte Finish", isPrimary: true, sortOrder: 1 },
      { id: "img-hk-2b", publicUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=1000&q=80", altText: "Gooseneck Pouring Coffee", isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-hk-2-m", cjVariantId: "CJ-V-KET-M", sku: "MY-KET-BLK", option1Name: "Color", option1Value: "Matte Black", price: 94.00, compareAtPrice: 125.00, costPrice: 38.00, shippingCost: 7.20, inventoryQuantity: 65, weight: 1200, isActive: true },
      { id: "var-hk-2-s", cjVariantId: "CJ-V-KET-S", sku: "MY-KET-SIL", option1Name: "Color", option1Value: "Brushed Steel", price: 94.00, compareAtPrice: 125.00, costPrice: 38.00, shippingCost: 7.20, inventoryQuantity: 40, weight: 1200, isActive: true },
    ],
    specifications: { "Volume": "0.9 Liters", "Power": "1200W Rapid Boil", "Temperature Range": "104°F - 212°F (40°C - 100°C)", "Material": "304 Stainless Steel" },
    features: ["PID temperature controller", "60-minute heat hold", "LCD target and current temperature readout", "Ergonomic silicone grip handle"],
  },
  {
    id: "prod-hk-3",
    slug: "ergonomic-bamboo-prep-station",
    name: "Solid Organic Bamboo Cutting & Culinary Prep Station",
    shortDescription: "Multifunctional bamboo board with sliding stainless steel prep trays.",
    description: "Crafted from end-grain organic Moso bamboo. Features deep juice perimeter grooves, silicone non-slip stabilizing feet, and integrated nesting food-grade stainless prep trays for effortless chopped ingredient segregation.",
    categoryId: "cat-home-kitchen",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "Bamboo Cutting & Prep Station | MYCHOICE.in",
    seoDescription: "Organic bamboo cutting board with sliding stainless prep containers.",
    baseCurrency: "USD",
    basePrice: 46.00,
    compareAtPrice: 62.00,
    cjProductId: "CJ-HK-003",
    cjProductSku: "CJ-BRD-PREP",
    productRating: 4.8,
    reviewCount: 29,
    images: [
      { id: "img-hk-3a", publicUrl: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&w=1000&q=80", altText: "Bamboo Cutting Station", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-hk-3-std", cjVariantId: "CJ-V-BRD-S", sku: "MY-BRD-STD", option1Name: "Size", option1Value: "Standard (16x12 in)", price: 46.00, compareAtPrice: 62.00, costPrice: 16.00, shippingCost: 6.00, inventoryQuantity: 90, weight: 1400, isActive: true },
      { id: "var-hk-3-pro", cjVariantId: "CJ-V-BRD-P", sku: "MY-BRD-PRO", option1Name: "Size", option1Value: "Chef Large (19x14 in)", price: 58.00, compareAtPrice: 75.00, costPrice: 21.00, shippingCost: 7.50, inventoryQuantity: 45, weight: 1900, isActive: true },
    ],
    specifications: { "Material": "100% Organic Moso Bamboo & 304 Stainless Steel", "Coating": "Food-grade natural mineral oil", "Trays": "2 Stainless Nesting Trays" },
    features: ["Natural antimicrobial bamboo", "Dual stainless catch containers", "Deep juice gutter reservoir", "Knife-friendly durable surface"],
  },

  // 2. PET SUPPLIES (3 products)
  {
    id: "prod-pet-1",
    slug: "orthopedic-memory-foam-pet-lounger",
    name: "Orthopedic Memory Foam Calming Pet Lounger",
    shortDescription: "Human-grade dual density orthopedic foam with removable velvet faux-fur cover.",
    description: "Engineered to alleviate joint stress in both growing pups and mature companions. The contoured supportive bolster rim provides neck alignment, while the memory foam core cushions pressure points. Waterproof inner lining with machine-washable outer velvet cover.",
    categoryId: "cat-pet-supplies",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "Orthopedic Memory Foam Pet Lounger | MYCHOICE.in",
    seoDescription: "Luxury orthopedic calming dog and cat bed with supportive memory foam bolsters.",
    baseCurrency: "USD",
    basePrice: 68.00,
    compareAtPrice: 89.00,
    cjProductId: "CJ-PET-001",
    cjProductSku: "CJ-BED-ORTHO",
    productRating: 4.92,
    reviewCount: 54,
    images: [
      { id: "img-pet-1a", publicUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=1000&q=80", altText: "Orthopedic Pet Bed Gray", isPrimary: true, sortOrder: 1 },
      { id: "img-pet-1b", publicUrl: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=1000&q=80", altText: "Dog Resting in Lounger", isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-pet-1-m", cjVariantId: "CJ-V-BED-M", sku: "MY-BED-MED-GRY", option1Name: "Size", option1Value: "Medium (30x20 in)", option2Name: "Color", option2Value: "Slate Grey", price: 68.00, compareAtPrice: 89.00, costPrice: 24.00, shippingCost: 8.50, inventoryQuantity: 70, weight: 1800, isActive: true },
      { id: "var-pet-1-l", cjVariantId: "CJ-V-BED-L", sku: "MY-BED-LRG-GRY", option1Name: "Size", option1Value: "Large (36x28 in)", option2Name: "Color", option2Value: "Slate Grey", price: 86.00, compareAtPrice: 110.00, costPrice: 32.00, shippingCost: 11.00, inventoryQuantity: 50, weight: 2500, isActive: true },
    ],
    specifications: { "Foam": "CertiPUR-US Orthopedic High Density", "Cover": "Machine Washable Micro-Plush Velvet", "Base": "Non-Skid Water-Resistant Rubber Dots" },
    features: ["Calming 360-degree bolster neck support", "Hypoallergenic waterproof internal core liner", "Relieves arthritis and hip dysplasia pressure"],
  },
  {
    id: "prod-pet-2",
    slug: "stainless-steel-pet-water-fountain",
    name: "Ultra-Quiet Stainless Steel Circulating Pet Fountain",
    shortDescription: "Hygienic 304 food-grade stainless steel with quad-action charcoal filtration.",
    description: "Veterinarian-recommended stainless construction eliminates chin acne caused by plastic bowls. Constant aerobic aeration provides crisp, oxygenated stream water that encourages optimal hydration in cats and small dogs.",
    categoryId: "cat-pet-supplies",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: true,
    seoTitle: "Stainless Steel Pet Water Fountain | MYCHOICE.in",
    seoDescription: "Hygienic quiet pet water fountain with 4-stage carbon filtration.",
    baseCurrency: "USD",
    basePrice: 39.00,
    compareAtPrice: 52.00,
    cjProductId: "CJ-PET-002",
    cjProductSku: "CJ-FOUNTAIN-SS",
    productRating: 4.88,
    reviewCount: 31,
    images: [
      { id: "img-pet-2a", publicUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=1000&q=80", altText: "Stainless Steel Pet Fountain", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-pet-2-std", cjVariantId: "CJ-V-FNT-SS", sku: "MY-FNT-SS", option1Name: "Capacity", option1Value: "2.5 Liters (84 oz)", price: 39.00, compareAtPrice: 52.00, costPrice: 14.50, shippingCost: 4.20, inventoryQuantity: 110, weight: 750, isActive: true },
    ],
    specifications: { "Capacity": "2.5L / 84 oz", "Pump Noise": "< 20 dB Submersible", "Material": "SUS 304 Food-Grade Stainless", "Power": "USB 5V Low Voltage" },
    features: ["Dishwasher-safe basin and lid", "Quad-stage active coconut carbon filter", "Submerged LED low-water auto shut-off indicator"],
  },
  {
    id: "prod-pet-3",
    slug: "hands-free-bungee-dog-leash",
    name: "Tactical Shock-Absorbing Hands-Free Running Leash",
    shortDescription: "Dual-handle shock-absorbing bungee leash with reflective 3M safety threads.",
    description: "Designed for active outdoor owners. Wear comfortably around your waist during jogs or use the secondary neoprene traffic handle for instant close-quarters control in busy urban streets. Absorbs sudden pulls up to 150 lbs.",
    categoryId: "cat-pet-supplies",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "Hands-Free Running Dog Leash | MYCHOICE.in",
    seoDescription: "Dual handle bungee shock-absorbing running leash with reflective safety stitching.",
    baseCurrency: "USD",
    basePrice: 28.00,
    compareAtPrice: 38.00,
    cjProductId: "CJ-PET-003",
    cjProductSku: "CJ-LEASH-BUNGEE",
    productRating: 4.79,
    reviewCount: 22,
    images: [
      { id: "img-pet-3a", publicUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=1000&q=80", altText: "Hands Free Leash Running", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-pet-3-blk", cjVariantId: "CJ-V-LSH-B", sku: "MY-LSH-BLK", option1Name: "Color", option1Value: "Stealth Black", price: 28.00, compareAtPrice: 38.00, costPrice: 8.50, shippingCost: 2.80, inventoryQuantity: 140, weight: 320, isActive: true },
      { id: "var-pet-3-olv", cjVariantId: "CJ-V-LSH-O", sku: "MY-LSH-OLV", option1Name: "Color", option1Value: "Alpine Olive", price: 28.00, compareAtPrice: 38.00, costPrice: 8.50, shippingCost: 2.80, inventoryQuantity: 95, weight: 320, isActive: true },
    ],
    specifications: { "Length": "48 in extends to 70 in", "Waist Belt": "Adjustable 27 to 48 in", "Hardware": "Aviation-grade Zinc Alloy swivel carabiner" },
    features: ["Dual padded control handles", "Heavy-duty tension bungee core", "3M high-visibility luminous reflective stitching"],
  },

  // 3. BEAUTY & PERSONAL CARE (3 products)
  {
    id: "prod-bpc-1",
    slug: "sonic-microcurrent-facial-device",
    name: "SculptPro Sonic Microcurrent Facial Toning Device",
    shortDescription: "Non-invasive anti-aging facial lifting tool with red light therapy.",
    description: "Replicate professional clinical facial contouring at home. Gentle microcurrent impulses stimulate facial muscles to visibly firm, tone, and lift the jawline and brow area while 630nm red phototherapy boosts natural collagen synthesis.",
    categoryId: "cat-beauty-personal-care",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "Sonic Microcurrent Facial Toning Device | MYCHOICE.in",
    seoDescription: "Clinical grade microcurrent facial toning device with 630nm red light therapy.",
    baseCurrency: "USD",
    basePrice: 89.00,
    compareAtPrice: 120.00,
    cjProductId: "CJ-BPC-001",
    cjProductSku: "CJ-DEV-MICRO",
    productRating: 4.94,
    reviewCount: 67,
    images: [
      { id: "img-bpc-1a", publicUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=80", altText: "Facial Sculpting Device", isPrimary: true, sortOrder: 1 },
      { id: "img-bpc-1b", publicUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1000&q=80", altText: "Facial Device in Hand", isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-bpc-1-wht", cjVariantId: "CJ-V-DEV-W", sku: "MY-DEV-WHT", option1Name: "Color", option1Value: "Pearl White", price: 89.00, compareAtPrice: 120.00, costPrice: 28.00, shippingCost: 4.50, inventoryQuantity: 80, weight: 260, isActive: true },
      { id: "var-bpc-1-pnk", cjVariantId: "CJ-V-DEV-P", sku: "MY-DEV-PNK", option1Name: "Color", option1Value: "Blush Rose", price: 89.00, compareAtPrice: 120.00, costPrice: 28.00, shippingCost: 4.50, inventoryQuantity: 60, weight: 260, isActive: true },
    ],
    specifications: { "Frequency": "8,000 VPM Sonic Oscillations", "Microcurrent": "330 uA Safe Grade", "Battery": "Rechargeable Li-ion 1200mAh (USB-C)", "Certifications": "CE, RoHS, FCC" },
    features: ["Visible 5-minute facial lift contouring", "Dual chrome therapeutic globes", "Red light LED collagen rejuvenation", "Smart ergonomic palm grip"],
  },
  {
    id: "prod-bpc-2",
    slug: "rose-quartz-sculpting-roller",
    name: "Grade-A Rose Quartz Lymphatic Sculpting & Gua Sha Duo",
    shortDescription: "Handcrafted 100% natural Brazilian rose quartz facial roller and contoured scraper.",
    description: "Carved from premium Brazilian rose quartz crystal. Regular use calms facial puffiness, facilitates lymphatic fluid drainage, and improves serum absorption for an instant lit-from-within glow.",
    categoryId: "cat-beauty-personal-care",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "Rose Quartz Gua Sha & Sculpting Roller | MYCHOICE.in",
    seoDescription: "Authentic Brazilian natural rose quartz facial roller and gua sha set.",
    baseCurrency: "USD",
    basePrice: 32.00,
    compareAtPrice: 45.00,
    cjProductId: "CJ-BPC-002",
    cjProductSku: "CJ-SET-QUARTZ",
    productRating: 4.87,
    reviewCount: 34,
    images: [
      { id: "img-bpc-2a", publicUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1000&q=80", altText: "Rose Quartz Roller Set", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-bpc-2-std", cjVariantId: "CJ-V-QTZ-S", sku: "MY-SET-QTZ", option1Name: "Material", option1Value: "Authentic Rose Quartz", price: 32.00, compareAtPrice: 45.00, costPrice: 9.80, shippingCost: 3.50, inventoryQuantity: 150, weight: 280, isActive: true },
    ],
    specifications: { "Stone Origin": "Minas Gerais, Brazil", "Frame": "Reinforced Zinc Alloy with Noise-Free Silicone Inserts", "Packaging": "Hardbound Gift Box" },
    features: ["Noise-free squeak-less rolling mechanism", "Naturally cool stone soothes skin inflammation", "Includes contoured wing gua sha stone"],
  },
  {
    id: "prod-bpc-3",
    slug: "negative-ion-ionic-hair-styler",
    name: "AeroSilk Negative Ion High-Speed Hair Styler & Dryer",
    shortDescription: "110,000 RPM brushless motor with 200 million negative ions for zero frizz.",
    description: "Engineered with intelligent thermal monitoring sensors measuring air temperature 50 times per second to prevent heat damage. High-density negative ion flow seals hair cuticles for mirror-like shine in half the drying time.",
    categoryId: "cat-beauty-personal-care",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: false,
    newArrival: true,
    seoTitle: "High-Speed Ionic Hair Dryer | MYCHOICE.in",
    seoDescription: "Brushless motor negative ion hair dryer with smart thermostatic heat guard.",
    baseCurrency: "USD",
    basePrice: 119.00,
    compareAtPrice: 169.00,
    cjProductId: "CJ-BPC-003",
    cjProductSku: "CJ-DRY-IONIC",
    productRating: 4.91,
    reviewCount: 45,
    images: [
      { id: "img-bpc-3a", publicUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=80", altText: "Ionic Hair Dryer", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-bpc-3-gry", cjVariantId: "CJ-V-DRY-G", sku: "MY-DRY-SLT", option1Name: "Color", option1Value: "Slate Grey & Champagne", price: 119.00, compareAtPrice: 169.00, costPrice: 42.00, shippingCost: 7.50, inventoryQuantity: 55, weight: 850, isActive: true },
      { id: "var-bpc-3-wht", cjVariantId: "CJ-V-DRY-W", sku: "MY-DRY-WHT", option1Name: "Color", option1Value: "Frosted White", price: 119.00, compareAtPrice: 169.00, costPrice: 42.00, shippingCost: 7.50, inventoryQuantity: 40, weight: 850, isActive: true },
    ],
    specifications: { "Motor Speed": "110,000 RPM Brushless", "Airflow": "22 m/s", "Ionic Density": "200M/cm3", "Weight": "407 grams featherweight" },
    features: ["Intelligent NTC heat sensing at 50x/sec", "Magnetic 360-degree concentrator nozzle", "Acoustic noise reduction under 60dB"],
  },

  // 4. ORNAMENTS & FASHION ACCESSORIES (3 products)
  {
    id: "prod-ofa-1",
    slug: "18k-gold-vermeil-geometric-pendant",
    name: "Aura 18K Gold Vermeil Geometric Compass Pendant",
    shortDescription: "Thick 2.5 micron 18K gold over 925 sterling silver with ethical lab sapphire.",
    description: "An homage to timeless seafaring navigation. Crafted in heavy 18 karat gold vermeil over a certified solid 925 sterling silver foundation. Features a faceted center white sapphire that catches natural daylight with subtle brilliance.",
    categoryId: "cat-ornaments-fashion-accessories",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "18K Gold Vermeil Geometric Compass Pendant | MYCHOICE.in",
    seoDescription: "Luxury 18K gold vermeil compass pendant with lab sapphire accent.",
    baseCurrency: "USD",
    basePrice: 72.00,
    compareAtPrice: 98.00,
    cjProductId: "CJ-OFA-001",
    cjProductSku: "CJ-JW-COMPASS",
    productRating: 4.96,
    reviewCount: 48,
    images: [
      { id: "img-ofa-1a", publicUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=80", altText: "Gold Compass Pendant", isPrimary: true, sortOrder: 1 },
      { id: "img-ofa-1b", publicUrl: "https://images.unsplash.com/photo-1611591475816-cb172778749a?auto=format&fit=crop&w=1000&q=80", altText: "Gold Necklace Detail", isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-ofa-1-g", cjVariantId: "CJ-V-JW-G", sku: "MY-JW-GLD", option1Name: "Finish", option1Value: "18K Yellow Gold Vermeil", price: 72.00, compareAtPrice: 98.00, costPrice: 22.00, shippingCost: 2.50, inventoryQuantity: 90, weight: 45, isActive: true },
      { id: "var-ofa-1-s", cjVariantId: "CJ-V-JW-S", sku: "MY-JW-SLV", option1Name: "Finish", option1Value: "Rhodium Sterling Silver", price: 68.00, compareAtPrice: 92.00, costPrice: 20.00, shippingCost: 2.50, inventoryQuantity: 75, weight: 45, isActive: true },
    ],
    specifications: { "Core Metal": "Solid 925 Sterling Silver", "Plating": "2.5 Micron 18 Karat Gold", "Chain Length": "18 inch + 2 inch extender", "Hypoallergenic": "Nickel & Lead Free" },
    features: ["Tarnish-resistant e-coat protection", "Lobster clasp closure with extension link", "Gift-ready velvet jewelry box included"],
  },
  {
    id: "prod-ofa-2",
    slug: "minimalist-ceramic-titanium-ring",
    name: "Architectural Zirconia Ceramic & Aerospace Titanium Band",
    shortDescription: "Ultra-scratch resistant black zirconia ceramic band with titanium inner core.",
    description: "Engineered comfort-fit ring uniting matte industrial black zirconia ceramic with a brushed aerospace-grade Grade-5 titanium core. Incredibly lightweight, scratch-impervious, and completely hypoallergenic.",
    categoryId: "cat-ornaments-fashion-accessories",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: true,
    seoTitle: "Ceramic & Titanium Unisex Ring Band | MYCHOICE.in",
    seoDescription: "Scratch-resistant zirconia ceramic and titanium architectural ring.",
    baseCurrency: "USD",
    basePrice: 52.00,
    compareAtPrice: 70.00,
    cjProductId: "CJ-OFA-002",
    cjProductSku: "CJ-RNG-TITAN",
    productRating: 4.86,
    reviewCount: 19,
    images: [
      { id: "img-ofa-2a", publicUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=80", altText: "Titanium Ceramic Ring", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-ofa-2-8", cjVariantId: "CJ-V-RNG-8", sku: "MY-RNG-SZ8", option1Name: "Ring Size", option1Value: "US 8", price: 52.00, compareAtPrice: 70.00, costPrice: 15.00, shippingCost: 2.20, inventoryQuantity: 60, weight: 20, isActive: true },
      { id: "var-ofa-2-9", cjVariantId: "CJ-V-RNG-9", sku: "MY-RNG-SZ9", option1Name: "Ring Size", option1Value: "US 9", price: 52.00, compareAtPrice: 70.00, costPrice: 15.00, shippingCost: 2.20, inventoryQuantity: 80, weight: 20, isActive: true },
      { id: "var-ofa-2-10", cjVariantId: "CJ-V-RNG-10", sku: "MY-RNG-SZ10", option1Name: "Ring Size", option1Value: "US 10", price: 52.00, compareAtPrice: 70.00, costPrice: 15.00, shippingCost: 2.20, inventoryQuantity: 70, weight: 20, isActive: true },
    ],
    specifications: { "Width": "6mm Comfort Edge", "Core": "Grade-5 Aerospace Titanium", "Exterior": "Black High-Tech Zirconia Ceramic" },
    features: ["Scratch proof and color permanent", "Featherlight comfort fit interior contour", "Safe for swimming and gym activities"],
  },
  {
    id: "prod-ofa-3",
    slug: "italian-leather-slim-rfid-cardholder",
    name: "Artisan Full-Grain Italian Leather RFID Card Wallet",
    shortDescription: "Slim handcrafted vegetable-tanned Italian leather with RFID signal block.",
    description: "Hand-stitched by leather artisans using full-grain Tuscan vegetable-tanned cowhide. Houses up to 8 cards with quick-access thumb pull-tab and folded bill compartment, all protected by a woven RFID electromagnetic shield.",
    categoryId: "cat-ornaments-fashion-accessories",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "Italian Leather Slim RFID Cardholder | MYCHOICE.in",
    seoDescription: "Full grain vegetable-tanned Italian leather minimalist cardholder with RFID protection.",
    baseCurrency: "USD",
    basePrice: 44.00,
    compareAtPrice: 60.00,
    cjProductId: "CJ-OFA-003",
    cjProductSku: "CJ-WLT-SLIM",
    productRating: 4.88,
    reviewCount: 37,
    images: [
      { id: "img-ofa-3a", publicUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=1000&q=80", altText: "Slim Leather Cardholder", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-ofa-3-cog", cjVariantId: "CJ-V-WLT-C", sku: "MY-WLT-COG", option1Name: "Leather Color", option1Value: "Cognac Tan", price: 44.00, compareAtPrice: 60.00, costPrice: 13.50, shippingCost: 2.50, inventoryQuantity: 95, weight: 70, isActive: true },
      { id: "var-ofa-3-obs", cjVariantId: "CJ-V-WLT-O", sku: "MY-WLT-OBS", option1Name: "Leather Color", option1Value: "Obsidian Black", price: 44.00, compareAtPrice: 60.00, costPrice: 13.50, shippingCost: 2.50, inventoryQuantity: 110, weight: 70, isActive: true },
    ],
    specifications: { "Leather": "100% Certified Full-Grain Tuscan Vegetable Tanned", "Capacity": "6-8 Cards + Cash", "Thickness": "0.3 inches empty" },
    features: ["Develops rich custom patina over time", "13.56 MHz RFID electromagnetic blocking layer", "Fast thumb swipe access slot"],
  },

  // 5. PHONE & TECH ACCESSORIES (3 products)
  {
    id: "prod-pta-1",
    slug: "3-in-1-magnetic-wireless-charging-station",
    name: "MagFold 3-in-1 Magnetic Fast Wireless Charging Dock",
    shortDescription: "Ultra-compact foldable aluminum station for iPhone, Apple Watch, and AirPods.",
    description: "Declutter your nightstand or workspace with this CNC machined aerospace aluminum wireless station. Strong N52 neodymium magnets snap phone securely into portrait or landscape StandBy orientation while delivering up to 15W Qi2 fast charging.",
    categoryId: "cat-phone-tech-accessories",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "3-in-1 Foldable Magnetic Wireless Charging Station | MYCHOICE.in",
    seoDescription: "Premium aluminum 3-in-1 foldable Qi2 magnetic wireless charger.",
    baseCurrency: "USD",
    basePrice: 69.00,
    compareAtPrice: 95.00,
    cjProductId: "CJ-PTA-001",
    cjProductSku: "CJ-CHG-MAG3",
    productRating: 4.93,
    reviewCount: 82,
    images: [
      { id: "img-pta-1a", publicUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1000&q=80", altText: "3 in 1 Magnetic Wireless Charger", isPrimary: true, sortOrder: 1 },
      { id: "img-pta-1b", publicUrl: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=1000&q=80", altText: "Foldable Travel Charger", isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-pta-1-spc", cjVariantId: "CJ-V-CHG-S", sku: "MY-CHG-SPC", option1Name: "Color", option1Value: "Space Titanium", price: 69.00, compareAtPrice: 95.00, costPrice: 23.00, shippingCost: 4.50, inventoryQuantity: 110, weight: 340, isActive: true },
      { id: "var-pta-1-slv", cjVariantId: "CJ-V-CHG-L", sku: "MY-CHG-SLV", option1Name: "Color", option1Value: "Starlight Silver", price: 69.00, compareAtPrice: 95.00, costPrice: 23.00, shippingCost: 4.50, inventoryQuantity: 85, weight: 340, isActive: true },
    ],
    specifications: { "Max Output": "Phone: 15W / Watch: 5W / Buds: 5W", "Input": "USB-C PD 30W+", "Dimensions Folded": "3.5 x 2.8 x 0.8 inches", "Weight": "210 grams" },
    features: ["Qi2 protocol certified 15W rapid wireless charge", "Folds completely flat for travel", "Supports iOS StandBy display mode"],
  },
  {
    id: "prod-pta-2",
    slug: "aerospace-aluminum-laptop-stand",
    name: "Architectural CNC Aluminum Laptop & Tablet Riser",
    shortDescription: "Ergonomic 360-degree rotating dual-axis aluminum riser for 10-17 inch laptops.",
    description: "Eliminate neck strain with a dual-hinge architectural aluminum stand. Features a satisfying mechanical click 360-degree rotating base, vented heat dissipation ports, and reinforced dampers supporting up to 10 kg without sagging.",
    categoryId: "cat-phone-tech-accessories",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: true,
    seoTitle: "Architectural Aluminum Laptop Riser Stand | MYCHOICE.in",
    seoDescription: "Heavy duty 360 rotating dual-hinge laptop stand in matte aluminum.",
    baseCurrency: "USD",
    basePrice: 48.00,
    compareAtPrice: 65.00,
    cjProductId: "CJ-PTA-002",
    cjProductSku: "CJ-STND-ALUM",
    productRating: 4.88,
    reviewCount: 39,
    images: [
      { id: "img-pta-2a", publicUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1000&q=80", altText: "Aluminum Laptop Stand", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-pta-2-gry", cjVariantId: "CJ-V-STND-G", sku: "MY-STND-GRY", option1Name: "Finish", option1Value: "Anodized Space Gray", price: 48.00, compareAtPrice: 65.00, costPrice: 17.00, shippingCost: 5.80, inventoryQuantity: 120, weight: 890, isActive: true },
      { id: "var-pta-2-slv", cjVariantId: "CJ-V-STND-S", sku: "MY-STND-SLV", option1Name: "Finish", option1Value: "Frosted Silver", price: 48.00, compareAtPrice: 65.00, costPrice: 17.00, shippingCost: 5.80, inventoryQuantity: 95, weight: 890, isActive: true },
    ],
    specifications: { "Compatibility": "All Laptops 10 to 17.3 inches", "Load Bearing": "Up to 22 lbs (10 kg)", "Material": "High-Density Sandblasted Anodized Aluminum" },
    features: ["Precision dampened dual-axis height tilt", "360-degree ball-bearing swivel turntable", "Silicone anti-scratch pads on all contact surfaces"],
  },
  {
    id: "prod-pta-3",
    slug: "ultra-slim-braided-100w-gan-cable-kit",
    name: "ArmorFlex 100W GaN Fast Charge Braided Cable Duo",
    shortDescription: "E-marker chipped Kevlar-reinforced 100W USB-C cable set with silicone organizers.",
    description: "Engineered to outlast standard OEM cables by 10x. Built with high-density ballistic nylon braiding, integrated E-Marker chipset for smart power regulation up to 100W, and gold-plated terminal contacts for rapid power delivery.",
    categoryId: "cat-phone-tech-accessories",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "100W GaN Braided USB-C Cable Duo | MYCHOICE.in",
    seoDescription: "Kevlar braided 100W fast charge USB-C cable kit with E-marker chip.",
    baseCurrency: "USD",
    basePrice: 24.00,
    compareAtPrice: 35.00,
    cjProductId: "CJ-PTA-003",
    cjProductSku: "CJ-CBL-100W",
    productRating: 4.82,
    reviewCount: 26,
    images: [
      { id: "img-pta-3a", publicUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=80", altText: "Braided Fast Charge Cable", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-pta-3-2m", cjVariantId: "CJ-V-CBL-2", sku: "MY-CBL-2M", option1Name: "Length", option1Value: "6.6 ft (2.0m) Pair", price: 24.00, compareAtPrice: 35.00, costPrice: 6.80, shippingCost: 2.20, inventoryQuantity: 180, weight: 140, isActive: true },
    ],
    specifications: { "Max Wattage": "100W (20V/5A) Power Delivery 3.0", "Data Transfer": "480 Mbps High Speed", "Bend Lifespan": "35,000+ Lab Tested Bends" },
    features: ["Smart E-Marker power negotiation chip", "Includes magnetic silicone cable tie clips", "Reinforced aluminum connector housing"],
  },

  // 6. FITNESS & WELLNESS (3 products)
  {
    id: "prod-fit-1",
    slug: "deep-tissue-percussion-massage-gun",
    name: "PulsePro Deep Tissue Percussion Therapy Massage Device",
    shortDescription: "12mm deep amplitude recovery tool with whisper-glide quiet motor.",
    description: "Designed in collaboration with physical therapists. Delivers 12mm penetrative stroke amplitude targeting deep muscle knots, accelerating post-workout lactic acid clearance, and alleviating chronic myofascial tension.",
    categoryId: "cat-fitness-wellness",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "Deep Tissue Percussion Massage Gun | MYCHOICE.in",
    seoDescription: "Professional 12mm amplitude percussion therapy massage gun with 5 heads.",
    baseCurrency: "USD",
    basePrice: 84.00,
    compareAtPrice: 115.00,
    cjProductId: "CJ-FIT-001",
    cjProductSku: "CJ-GUN-PERC",
    productRating: 4.95,
    reviewCount: 71,
    images: [
      { id: "img-fit-1a", publicUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1000&q=80", altText: "Percussion Massage Gun", isPrimary: true, sortOrder: 1 },
      { id: "img-fit-1b", publicUrl: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1000&q=80", altText: "Massage Gun Attachments", isPrimary: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-fit-1-blk", cjVariantId: "CJ-V-GUN-B", sku: "MY-GUN-BLK", option1Name: "Finish", option1Value: "Matte Carbon Black", price: 84.00, compareAtPrice: 115.00, costPrice: 27.00, shippingCost: 6.50, inventoryQuantity: 95, weight: 920, isActive: true },
    ],
    specifications: { "Stroke Amplitude": "12mm Deep Penetration", "Speed Levels": "5 Variable Speeds (1400-3200 RPM)", "Battery": "6 Hours Continuous Run (2600mAh)", "Attachments": "5 Ergonomic Massage Heads" },
    features: ["Brushless Quiet-Glide 42dB technology", "Includes hard-shell EVA ballistic carry case", "LCD real-time pressure sensor display"],
  },
  {
    id: "prod-fit-2",
    slug: "non-slip-natural-cork-yoga-mat",
    name: "AuraEarth Non-Slip Organic Cork & Tree Rubber Yoga Mat",
    shortDescription: "Antimicrobial sustainable cork surface with natural rubber grip foundation.",
    description: "Experience grounding naturally. Organic harvested cork gains superior grip the more you sweat, while the 4.5mm natural tree rubber base anchors firmly to studio hardwood without bunching. Contains zero PVC, phthalates, or toxic glues.",
    categoryId: "cat-fitness-wellness",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: true,
    seoTitle: "Organic Cork & Tree Rubber Yoga Mat | MYCHOICE.in",
    seoDescription: "Naturally antimicrobial non-slip organic cork yoga mat with laser body alignment lines.",
    baseCurrency: "USD",
    basePrice: 56.00,
    compareAtPrice: 75.00,
    cjProductId: "CJ-FIT-002",
    cjProductSku: "CJ-MAT-CORK",
    productRating: 4.89,
    reviewCount: 38,
    images: [
      { id: "img-fit-2a", publicUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1000&q=80", altText: "Cork Yoga Mat Grounding", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-fit-2-align", cjVariantId: "CJ-V-MAT-A", sku: "MY-MAT-ALIGN", option1Name: "Style", option1Value: "Laser Alignment Grid", price: 56.00, compareAtPrice: 75.00, costPrice: 18.00, shippingCost: 7.00, inventoryQuantity: 80, weight: 2100, isActive: true },
    ],
    specifications: { "Dimensions": "72 in x 26 in (183cm x 66cm)", "Thickness": "4.5mm Joint Cushioning", "Materials": "100% Organic Cork & Biodegradable Tree Rubber" },
    features: ["Naturally odor-resistant & self-sanitizing", "Laser-etched posture alignment guidance system", "Complimentary woven cotton carry strap"],
  },
  {
    id: "prod-fit-3",
    slug: "smart-digital-resistance-jump-rope",
    name: "OrbitPulse Smart Digital Weighted Jump Rope",
    shortDescription: "Dual-mode cordless and steel-cable smart jump rope with Bluetooth tracking.",
    description: "Switch seamlessly between outdoor 3-meter steel cable jumping and indoor silent cordless weighted balls. Built-in dual hall sensors accurately track your rotations, calorie burn, and workout duration on an integrated backlit LED display.",
    categoryId: "cat-fitness-wellness",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "Smart Digital Weighted Jump Rope | MYCHOICE.in",
    seoDescription: "Dual-mode cordless and cable smart jump rope with LCD rotation counter.",
    baseCurrency: "USD",
    basePrice: 34.00,
    compareAtPrice: 48.00,
    cjProductId: "CJ-FIT-003",
    cjProductSku: "CJ-RPE-SMART",
    productRating: 4.77,
    reviewCount: 24,
    images: [
      { id: "img-fit-3a", publicUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1000&q=80", altText: "Digital Jump Rope", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-fit-3-blk", cjVariantId: "CJ-V-RPE-B", sku: "MY-RPE-BLK", option1Name: "Color", option1Value: "Matte Charcoal", price: 34.00, compareAtPrice: 48.00, costPrice: 10.50, shippingCost: 3.50, inventoryQuantity: 110, weight: 380, isActive: true },
    ],
    specifications: { "Bearing": "360-degree Low Friction Stainless Steel", "Display": "High-contrast LED Screen", "Weight Blocks": "Dual 60g Removable Handle Weights" },
    features: ["Switch between rope and cordless balls", "Precision dual-hall magnetic jump counting", "Silicone non-slip sweat-resistant handles"],
  },

  // 7. ECO-FRIENDLY & SUSTAINABLE (3 products)
  {
    id: "prod-eco-1",
    slug: "insulated-ceramic-travel-tumbler",
    name: "PureTaste Double-Wall Ceramic Lined Travel Tumbler",
    shortDescription: "Vacuum-insulated stainless tumbler with true ceramic interior lining.",
    description: "Say goodbye to metallic coffee aftertaste. Featuring a true porcelain ceramic interior coating bonded to a double-wall vacuum stainless exterior. Keeps cold brew chilled for 24 hours and piping hot espresso warm for 12 hours.",
    categoryId: "cat-eco-friendly-sustainable",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "Ceramic Lined Vacuum Travel Tumbler | MYCHOICE.in",
    seoDescription: "Vacuum insulated stainless steel tumbler with pure ceramic interior.",
    baseCurrency: "USD",
    basePrice: 38.00,
    compareAtPrice: 50.00,
    cjProductId: "CJ-ECO-001",
    cjProductSku: "CJ-TUM-CERAM",
    productRating: 4.92,
    reviewCount: 46,
    images: [
      { id: "img-eco-1a", publicUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1000&q=80", altText: "Ceramic Travel Tumbler", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-eco-1-cl", cjVariantId: "CJ-V-TUM-C", sku: "MY-TUM-CLY", option1Name: "Color", option1Value: "Warm Clay", price: 38.00, compareAtPrice: 50.00, costPrice: 11.50, shippingCost: 4.20, inventoryQuantity: 130, weight: 410, isActive: true },
      { id: "var-eco-1-sl", cjVariantId: "CJ-V-TUM-S", sku: "MY-TUM-SLT", option1Name: "Color", option1Value: "Slate Obsidian", price: 38.00, compareAtPrice: 50.00, costPrice: 11.50, shippingCost: 4.20, inventoryQuantity: 95, weight: 410, isActive: true },
    ],
    specifications: { "Capacity": "16 oz (475ml)", "Insulation": "Double-Wall Vacuum Sealed", "Interior": "True Ceramic Glaze", "Lid": "100% Leak-Proof Slide Seal" },
    features: ["Zero metallic flavor transfer", "Cup holder friendly silhouette", "BPA-free splash proof lid"],
  },
  {
    id: "prod-eco-2",
    slug: "zero-waste-organic-beeswax-wraps",
    name: "Artisan Organic Beeswax Food Storage Wraps (Pack of 5)",
    shortDescription: "Zero-waste reusable breathable wraps made from organic cotton and jojoba oil.",
    description: "Replace single-use plastic cling wrap forever. Hand-dipped in organic beeswax, sustainably harvested tree resin, and cold-pressed jojoba oil. Warm with the heat of your hands to seal over bowls, cheese, fresh sourdough, and produce.",
    categoryId: "cat-eco-friendly-sustainable",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "Organic Beeswax Reusable Food Wraps | MYCHOICE.in",
    seoDescription: "Pack of 5 zero waste organic beeswax and jojoba oil food wraps.",
    baseCurrency: "USD",
    basePrice: 22.00,
    compareAtPrice: 32.00,
    cjProductId: "CJ-ECO-002",
    cjProductSku: "CJ-WRP-BEES",
    productRating: 4.84,
    reviewCount: 31,
    images: [
      { id: "img-eco-2a", publicUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80", altText: "Organic Beeswax Wraps", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-eco-2-set", cjVariantId: "CJ-V-WRP-5", sku: "MY-WRP-SET5", option1Name: "Set", option1Value: "5 Assorted Sizes (S, M, L, XL)", price: 22.00, compareAtPrice: 32.00, costPrice: 6.20, shippingCost: 2.00, inventoryQuantity: 160, weight: 180, isActive: true },
    ],
    specifications: { "Ingredients": "GOTS Organic Cotton, Pure Beeswax, Organic Jojoba Oil, Tree Resin", "Durability": "Reusable 120-150 times", "Care": "Wash with cold water and mild soap" },
    features: ["100% biodegradable and home compostable", "Naturally antimicrobial and breathable", "Eliminates disposable cling plastic waste"],
  },
  {
    id: "prod-eco-3",
    slug: "natural-wheat-straw-bento-lunch-box",
    name: "Kanso Minimalist Natural Wheat Straw Bento Lunch Box",
    shortDescription: "Plant-fiber dual layer meal prep box with wooden cutlery set.",
    description: "Crafted from upcycled reclaimed wheat straw fibers. Features two stackable leak-proof compartments, removable portion dividers, and a snug silicone airtight seal held firmly by an elastic canvas band. Comes with matching reusable utensils.",
    categoryId: "cat-eco-friendly-sustainable",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: true,
    seoTitle: "Natural Wheat Straw Bento Box | MYCHOICE.in",
    seoDescription: "Eco-friendly natural wheat straw fiber bento lunch box with cutlery set.",
    baseCurrency: "USD",
    basePrice: 26.00,
    compareAtPrice: 36.00,
    cjProductId: "CJ-ECO-003",
    cjProductSku: "CJ-BENTO-WHEAT",
    productRating: 4.81,
    reviewCount: 22,
    images: [
      { id: "img-eco-3a", publicUrl: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=1000&q=80", altText: "Wheat Straw Bento Box", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-eco-3-crm", cjVariantId: "CJ-V-BTO-C", sku: "MY-BTO-CRM", option1Name: "Color", option1Value: "Natural Cream", price: 26.00, compareAtPrice: 36.00, costPrice: 7.50, shippingCost: 3.20, inventoryQuantity: 120, weight: 360, isActive: true },
      { id: "var-eco-3-mch", cjVariantId: "CJ-V-BTO-M", sku: "MY-BTO-MCH", option1Name: "Color", option1Value: "Sage Matcha", price: 26.00, compareAtPrice: 36.00, costPrice: 7.50, shippingCost: 3.20, inventoryQuantity: 90, weight: 360, isActive: true },
    ],
    specifications: { "Material": "Upcycled Wheat Straw Fiber & Food Grade PP", "Capacity": "1200ml Dual Tier", "Microwave & Dishwasher Safe": "Yes (Top Rack)" },
    features: ["Includes fork, spoon, and chopsticks in lid compartment", "Airtight silicone leak-resistant sealing gaskets", "BPA-free non-toxic food safe materials"],
  },

  // 8. BABY & KIDS (3 products)
  {
    id: "prod-bk-1",
    slug: "silicone-suction-feeding-set",
    name: "PureSilicone Toddler Feeding & Self-Weaning Set (6-Piece)",
    shortDescription: "100% food-grade platinum silicone suction plate, bowl, cup, bib, and spoons.",
    description: "Designed to encourage independent toddler self-feeding without the messy spills. Powerful suction bases anchor plate and bowl securely to high chair trays. Soft flexible silicone protects tender gums while resisting stains and odors.",
    categoryId: "cat-baby-kids",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: true,
    bestseller: true,
    newArrival: false,
    seoTitle: "Silicone Suction Baby Feeding Set | MYCHOICE.in",
    seoDescription: "Platinum food grade silicone suction plate, bowl, bib, and spoon set.",
    baseCurrency: "USD",
    basePrice: 36.00,
    compareAtPrice: 49.00,
    cjProductId: "CJ-BK-001",
    cjProductSku: "CJ-SET-FEEDING",
    productRating: 4.96,
    reviewCount: 58,
    images: [
      { id: "img-bk-1a", publicUrl: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1000&q=80", altText: "Silicone Baby Feeding Set", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-bk-1-euc", cjVariantId: "CJ-V-FEED-E", sku: "MY-FEED-EUC", option1Name: "Colorway", option1Value: "Eucalyptus Green", price: 36.00, compareAtPrice: 49.00, costPrice: 11.00, shippingCost: 3.80, inventoryQuantity: 140, weight: 480, isActive: true },
      { id: "var-bk-1-snd", cjVariantId: "CJ-V-FEED-S", sku: "MY-FEED-SND", option1Name: "Colorway", option1Value: "Warm Sand", price: 36.00, compareAtPrice: 49.00, costPrice: 11.00, shippingCost: 3.80, inventoryQuantity: 110, weight: 480, isActive: true },
    ],
    specifications: { "Material": "100% Platinum LFGB Food-Grade Silicone", "Certifications": "BPA, BPS, PVC, Phthalate Free", "Safety": "Microwave, Dishwasher, Freezer Safe (-40°C to 220°C)" },
    features: ["Super strong vacuum suction bases", "Deep pocket food-catching adjustable bib", "Soft chewable training spoon and fork"],
  },
  {
    id: "prod-bk-2",
    slug: "organic-muslin-cotton-swaddle-bundle",
    name: "CloudSoft GOTS Organic Muslin Swaddle Blanket Bundle (3-Pack)",
    shortDescription: "Ultra-breathable 100% GOTS certified organic muslin cotton swaddles.",
    description: "Woven from extra-long staple certified organic Turkish cotton. The airy open weave regulates baby body temperature to prevent overheating, while getting softer and fluffier with every laundering. Generous 47x47 inch dimensions allow secure swaddling.",
    categoryId: "cat-baby-kids",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: true,
    seoTitle: "Organic Muslin Cotton Swaddle Bundle | MYCHOICE.in",
    seoDescription: "Set of 3 extra-large GOTS organic muslin cotton baby swaddles.",
    baseCurrency: "USD",
    basePrice: 38.00,
    compareAtPrice: 52.00,
    cjProductId: "CJ-BK-002",
    cjProductSku: "CJ-SWD-ORGANIC",
    productRating: 4.93,
    reviewCount: 41,
    images: [
      { id: "img-bk-2a", publicUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=80", altText: "Muslin Swaddle Blankets", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-bk-2-bot", cjVariantId: "CJ-V-SWD-B", sku: "MY-SWD-BOT", option1Name: "Print", option1Value: "Botanical Earth Set", price: 38.00, compareAtPrice: 52.00, costPrice: 12.00, shippingCost: 3.50, inventoryQuantity: 95, weight: 520, isActive: true },
    ],
    specifications: { "Dimensions": "47 in x 47 in (120cm x 120cm)", "Fabric": "100% GOTS Certified Organic Cotton", "Dyes": "Non-toxic azo-free natural pigments" },
    features: ["Multi-use: nursing cover, stroller shade, burp cloth", "Thermoregulating open muslin weave", "Machine washable durable hem stitching"],
  },
  {
    id: "prod-bk-3",
    slug: "portable-white-noise-sound-machine",
    name: "LullabyAcoustic Portable White Noise Machine & Night Light",
    shortDescription: "24 soothing acoustic profiles with breathable warm amber night light.",
    description: "Engineered to promote deep infant circadian rhythms. Houses 24 non-looping high-fidelity nature sounds and pink/brown noise frequencies that mask household disruptions. Compact rechargeable design clips conveniently to strollers or crib rails.",
    categoryId: "cat-baby-kids",
    brandName: "MYCHOICE",
    status: "published",
    riskStatus: "normal",
    featured: false,
    bestseller: false,
    newArrival: false,
    seoTitle: "Portable White Noise Sound Machine | MYCHOICE.in",
    seoDescription: "Rechargeable sound machine with 24 non-looping sounds and warm amber night light.",
    baseCurrency: "USD",
    basePrice: 42.00,
    compareAtPrice: 58.00,
    cjProductId: "CJ-BK-003",
    cjProductSku: "CJ-SND-NOISE",
    productRating: 4.88,
    reviewCount: 35,
    images: [
      { id: "img-bk-3a", publicUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1000&q=80", altText: "Baby Sound Machine Night Light", isPrimary: true, sortOrder: 1 },
    ],
    variants: [
      { id: "var-bk-3-wht", cjVariantId: "CJ-V-SND-W", sku: "MY-SND-WHT", option1Name: "Color", option1Value: "Ivory White", price: 42.00, compareAtPrice: 58.00, costPrice: 13.50, shippingCost: 3.20, inventoryQuantity: 110, weight: 260, isActive: true },
    ],
    specifications: { "Sounds": "24 Profiles (White/Pink/Brown noise, Heartbeat, Ocean)", "Battery Life": "Up to 30 Hours (USB-C Rechargeable)", "Timer": "30, 60, 90 mins or Continuous" },
    features: ["Child-safe soft silicone lanyard loop", "Warm amber circadian night light", "Memory function restores last volume & tone"],
  },
];

export const DEMO_COUPONS = [
  {
    id: "cpn-1",
    code: "WELCOME10",
    description: "10% off your inaugural order",
    discountType: "percentage" as const,
    discountValue: 10,
    minimumOrderValue: 50,
    maximumDiscount: 30,
    isActive: true,
  },
  {
    id: "cpn-2",
    code: "SAVE20",
    description: "$20 off orders exceeding $120",
    discountType: "fixed" as const,
    discountValue: 20,
    minimumOrderValue: 120,
    maximumDiscount: null,
    isActive: true,
  },
  {
    id: "cpn-3",
    code: "LUXURY25",
    description: "25% VIP savings on seasonal essentials",
    discountType: "percentage" as const,
    discountValue: 25,
    minimumOrderValue: 200,
    maximumDiscount: 75,
    isActive: true,
  },
];
